# Default values for SiteWhere Database infrastructure components.
mongodb:
  usePassword: false
  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
  persistence:
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    storage: 10Gi
cassandra:
  enabled: false
  persistence:
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 10Gi
influxdb:
  enabled: false
  persistence:
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 10Gi
