apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sitewheres.sitewhere.io
spec:
  group: sitewhere.io
  names:
    kind: SiteWhere
    listKind: SiteWhereList
    plural: sitewheres
    singular: sitewhere
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
