apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitewhere-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sitewhere-helm-operator
  template:
    metadata:
      labels:
        name: sitewhere-helm-operator
    spec:
      serviceAccountName: sitewhere-helm-operator
      containers:
        - name: sitewhere-helm-operator
          # Replace this with the built image name
          image: docker.io/jorgevillaverde/sitewhere-helm-operator:v0.1.0
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sitewhere-helm-operator"
